name: check
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: tj-actions/changed-files@v22.2
        id: files
        with:
          files: streams/*.m3u
      - uses: actions/setup-node@v2
        if: ${{ steps.files.outputs.any_changed == 'true' }}
        with:
          node-version: '14'
      - name: Validate M3U
        if: steps.files.outputs.any_changed == 'true'
        run: |
          npm install
          npm run playlist:lint -- ${{ steps.files.outputs.all_changed_files }}
          npm run playlist:validate -- ${{ steps.files.outputs.all_changed_files }}